name: unforge
description: >
  Download a branch, tag or commit from a git repository and extract it to a
  directory, without `git`. When you do not need history, this is quicker than
  using action/checkout.
author: Emmanuel Frecon <efrecon+github@gmail.com>
branding:
  icon: download
  color: blue

inputs:
  repository:
    description: 'Repository name with owner. For example, `efrecon/unforge`.'
    default: ${{ github.repository }}
  ref:
    description: >
      The branch, tag or SHA to checkout. When checking out the repository that
      triggered a workflow, this defaults to the reference or SHA for that
      event.  Otherwise, uses the default branch.
  token:
    description: >
      The token to use to access the repository at the remote/local forge.
      Defaults to the token of the workflow.
    default: ${{ github.token }}
  type:
    description: >
      The type of the forge to download from, one of `github` or `gitlab`
    default: github
  path:
    description: 'Relative path under $GITHUB_WORKSPACE to place the repository'
    required: false
  subdirectory:
    description: 'Subdirectory to extract from the remote repository'
    required: false
runs:
  using: composite
  steps:
    - name: Download
      id: download
      shell: bash
      # Pass the inputs to the action as environment variables. More secure:
      # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#understanding-the-risk-of-script-injections
      env:
        UNFORGE_TOKEN: ${{ inputs.token }}
        UNFORGE_TYPE: ${{ inputs.type }}
        UNFORGE__REF: ${{ inputs.ref }}
        UNFORGE__REPOSITORY: ${{ inputs.repository }}
        UNFORGE__PATH: ${{ inputs.path }}
        UNFORGE__SUBDIR: ${{ inputs.subdirectory }}
      run: |
        set -eu;  # Exit on error or undefined variable

        # Decide upon the reference to use
        if [ -z "$UNFORGE__REF" ] && [ "$UNFORGE__REPOSITORY" = '${{ github.repository}}' ]; then
          UNFORGE__REF=${{ github.ref }}
        fi

        # Use reference to decide upon the repository specification
        if [ -z "$UNFORGE__REF" ]; then
          repo=$UNFORGE__REPOSITORY
        else
          repo=${UNFORGE__REPOSITORY}@${UNFORGE__REF}
        fi

        # Construct target directory
        if [ -z "$UNFORGE__PATH" ]; then
          target=${GITHUB_WORKSPACE%/}
        else
          target="${GITHUB_WORKSPACE%/}/${UNFORGE__PATH}"
        fi

        "${{ github.action_path }}/unforge.sh" \
          -c '' \
          -f \
          -i '-' \
          -vv \
          add "$repo" "$target" "$UNFORGE__SUBDIR"
