---
  name: unforge

  on:
    push:

    pull_request:
      branches:
        - main
        - master
        - feature/**/main
        - feature/**/master
  concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

  jobs:
    unforge:
      runs-on: ubuntu-latest
      name: unforge
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: unforge
          uses: ./
          env:
            UNFORGE_INDEX: "-"
          with:
            path: __unforge__
        - name: result
          shell: bash
          run: |
            ls -lRh __unforge__